config/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_view

app_name = "core"
urlpatterns = [path("", room_view.all_rooms, name="home")]

rooms/urls.py
from django.urls import path
from rooms import views as room_view

app_name = "rooms"
# function
# urlpatterns = [path("<int:pk>", room_view.room_detail, name="detail")]
# class
urlpatterns = [
    path("<int:pk>", room_view.RoomDetail.as_view(), name="detail"),
    path("search", room_view.Search.as_view(), name="search"),
]

rooms/models.py
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from core import models as core_models

# Create your models here.
class AbstractItem(core_models.TimeStampedModel):
    """AbstractItem"""

    name = models.CharField(max_length=140, blank=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class Amenity(AbstractItem):

    """Amenity"""

    class Meta:
        verbose_name_plural = "Amenities"


class RoomType(AbstractItem):
    """RoomType"""

    class Meta:
        verbose_name = "Room Type"


class Facility(AbstractItem):
    """Facility"""

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):
    """HouseRule"""

    class Meta:
        verbose_name = "House Rule"


class Photo(core_models.TimeStampedModel):
    """Photo"""

    caption = models.CharField(max_length=140)
    file = models.ImageField(upload_to="rooms")
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(core_models.TimeStampedModel):
    """Room Model Definition"""

    name = models.CharField(max_length=140)
    discroption = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=100)
    price = models.IntegerField()
    address = models.CharField(max_length=100)
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    guests = models.IntegerField(default=1)
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        "users.User", related_name="rooms", on_delete=models.CASCADE
    )
    room_type = models.ForeignKey(
        "RoomType", related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    amenities = models.ManyToManyField("Amenity", related_name="rooms", blank=True)
    facilities = models.ManyToManyField("Facility", related_name="rooms", blank=True)
    house_rules = models.ManyToManyField("HouseRule", related_name="rooms", blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.rating_average()
            return round(all_ratings / len(all_reviews), 2)
        return 0

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):
    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="KR").formfield()

    room_type = forms.ModelChoiceField(
        required=False, empty_label="Any Kind", queryset=models.RoomType.objects.all()
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    super_host = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    facilities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

rooms/views.py
from random import choices
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import Http404
from django.views.generic import DetailView, View
from django_countries import countries
from django.core.paginator import Paginator
from . import models, forms


# Create your views here.


def all_rooms(request):
    page = request.GET.get("page")
    room_list = models.Room.objects.all()
    paginator = Paginator(room_list, 10, orphans=5)
    rooms = paginator.get_page(page)
    return render(
        request,
        "rooms/home.html",
        {"rooms": rooms},
    )


# function
"""def room_detail(request, pk):
    try:
        room = models.Room.objects.get(pk=pk)
        return render(request, "rooms/room_detail.html", {"room": room})

    except models.Room.DoesNotExist:
        raise Http404()"""
# class
class RoomDetail(DetailView):

    model = models.Room


class Search(View):
    def get(self, request):

        country = request.GET.get("country")

        if country:

            form = forms.SearchForm(request.GET)

            if form.is_valid():

                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if baths is not None:
                    filter_args["baths__gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True

                if superhost is True:
                    filter_args["host__superhost"] = True

                for amenity in amenities:
                    filter_args["amenities"] = amenity

                for facility in facilities:
                    filter_args["facilities"] = facility

                qs = models.Room.objects.filter(**filter_args).order_by("-create")
                paginator = Paginator(qs, 10, orphans=5)

                page = request.GET.get("page", 1)

                rooms = paginator.get_page(page)
                return render(
                    request, "rooms/search.html", {"form": form, "rooms": rooms}
                )
        else:
            form = forms.SearchForm()
        return render(
            request,
            "rooms/search.html",
            {"form": form},
        )

templates/rooms/home.html
{% extends "base.html" %}

{% block page_title %}Home{% endblock page_title %}



{%block content%}

{%for room in rooms%}
    <h1>
        <a href = "{% url "rooms:detail" room.pk%}">
        {{room.name}}/ {{room.price}}
        </a>
    </h1>
{%endfor%}
{% if rooms.has_previous%}
<a href = "?page={{rooms.previous_page_number}}">Previous</a>
{% endif %}
page: {{rooms.number}} of {{rooms.paginator.num_pages}}
{% if rooms.has_next%}
<a href = "?page={{rooms.next_page_number}}">Next</a>
{% endif %}
{%endblock content%}

templates/rooms/room_detail.html
{% extends "base.html" %}

{% block page_title %}{{room.name}}{% endblock page_title %}



{%block content%}
<div>
    <h1>{{room.name}}</h1>
    <h3>{{room.description}}</h3>
</div>
<div>
    <h2> By:{{room.host.username}}
    {% if room.host.superhost %}
        (suerhost)
    {% endif %}
    </h2>
    <h3>Amenities</h3>
    <ul>
        {% for it in room.amenities.all %}
        <li> {{it}}</li>
        {% endfor %}
    </ul>
    <h3>Facilities</h3>
    <ul>
        {% for it in room.facilities.all %}
        <li> {{it}}</li>
        {% endfor %}
    </ul>
    <h3>House Rules</h3>
    <ul>
        {% for it in room.house_rules.all %}
        <li> {{it}}</li>
        {% endfor %}
    </ul>
</div>
{%endblock content%}

templates/rooms/search.html
{% extends "base.html" %}

{% block page_title %}
Search
{% endblock page_title %}

{% block search-bar %}

{% endblock search-bar %}


{%block content%}
<form method="get" action="{% url "rooms:search" %}">
    <div>
        <label for="city">City</label>
        <input value="{{city}}" id="city" name="city" placeholder="Search By City" />
    </div>

    <div>
        <label for="country">Country</label>
        <select id="country" name="country" >
            {% for country in countries  %}
                <option value="{{country.code}}">{{country.name}}</option>
            {% endfor %}
        </select>
    </div>

    <div>
        <label for="room_type">Room Type</label>
        <select id="room_type" name="room_type" >
            {% for room_type in room_types  %}
                <option value="{{room_type.pk}}">{{room_type.name}}</option>
            {% endfor %}
        </select>
    </div>
    <button>Search</button>
</form>

{%endblock content%}