config/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_view

app_name = "core"
urlpatterns = [path("", room_view.all_rooms, name="home")]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("login", views.loginview.as_view(), name="login"),
    path("login/github", views.github_login, name="github-login"),
    path("login/github/callback", views.github_callback, name="github-callback"),
    path("login/kakao", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback", views.kakao_callback, name="kakao-callback"),
    path("logout", views.log_out, name="logout"),
    path("signup", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>", views.complete_verification, name="signup"),
]

templates/partial/footer.html
<footer>
    &copy: BnB
</footer>

templates/partial/nav.html
<a href="{% url "core:home" %}">BnB</a>
<ul>
    {% if user.is_authenticated %}
        <li><a href="{% url "users:logout" %}">Log out</a></li>
    {% else %}
        <li><a href="{% url "users:login" %}">Log in</a></li>
        <li><a href="{% url "users:signup" %}">Sign up</a></li>
    {% endif %}
</ul>

templates/partial/social_login.html
<div>
    <a href="{% url 'users:github-login' %}">
        Continue with Github
    </a>
    <a href="{% url 'users:kakao-login' %}">
        Continue with Kakao
    </a>
</div> 